export const mockEmployee = {
  id: 1,
  pdmId: 1,
  firstName: "Stefano",
  lastName: "Fiorenza",
  internationalName: "Stefano Fiorenza",
  title: "Learning Manager",
  email: "stefano.fiorenza@email.it",
  managementGroup: "IT",
  companyCode: "JHI HM-GP",
  businessUnit: "IT",
  costCenter: "KVL33JF",
  companyPhone: "990-210-7534",
  companyMobilePhone: "997-689-4855",
  gender: "Male",
  nationality: "Italy",
  office: {
    countryiso3: "EET",
    city: "Tallinn",
    street: "10195 Tartu Mnt 12",
    postalCode: null,
    country: "Estonia",
  },
  birthDate: "19/07/1989",
  startDate: "25/08/1990",
  onboardingDate: "29/04/2021",
  offboardingDate: "18/01/2021",
  endDate: null,
  dateOfLeave: null,
  groups: [3, 1],
  roleId: 5,
};
